// src/renderer/components/chat/ConfirmCard.tsx
import { Button, Group, Paper, Stack, Text, Badge } from '@mantine/core'

import type { ReactNode } from 'react'

// 确认卡（React 版 ConfirmCard.vue）：策略引擎的 confirm 请求上屏卡片。
// 多态 request 形状推断契约保持一致：专有 kind（类目创建/映射）+ 通用 payload/arguments，
// tool_name/toolName camelCase/snake_case 双容忍。

export interface ConfirmRequest {
  title?: string
  kind?: string
  tool_name?: string
  toolName?: string
  reason?: string
  details?: Array<string | null>
  domain?: string
  proposedCategoryName?: string
  recommendedCategory?: { name?: string } | null
  similarCandidates?: Array<{ name?: string } | null>
  pendingAction?: { toolName?: string } | null
  payload?: Record<string, unknown>
  arguments?: Record<string, unknown>
  [key: string]: unknown
}

function getTitle(request: ConfirmRequest): string {
  if (request?.title) return request.title
  if (request?.kind === 'category_creation_confirmation') return '确认新建这个类目'
  if (request?.kind === 'category_mapping_confirmation') return '确认改用这个类目'
  if (request?.tool_name) return `继续执行 ${request.tool_name}？`
  if (request?.toolName) return `继续执行 ${request.toolName}？`
  return '需要你确认'
}

function getReason(request: ConfirmRequest): string {
  return request?.reason || '需要你确认后继续'
}

function getDetails(request: ConfirmRequest): string[] {
  if (Array.isArray(request?.details) && request.details.length > 0) {
    return request.details.filter((item): item is string => typeof item === 'string' && item.length > 0)
  }

  if (request?.kind === 'category_creation_confirmation') {
    return [
      `所属领域：${request.domain || '未提供'}`,
      `建议类目：${request.proposedCategoryName || '未提供'}`,
      // 触发动作双容忍：pendingAction.toolName / toolName / tool_name
      `触发动作：${request.pendingAction?.toolName || request.toolName || request.tool_name || '未提供'}`,
    ]
  }

  if (request?.kind === 'category_mapping_confirmation') {
    const candidates = Array.isArray(request?.similarCandidates)
      ? request.similarCandidates.map((item) => item?.name).filter(Boolean)
      : []
    return [
      `所属领域：${request.domain || '未提供'}`,
      `推荐类目：${request.recommendedCategory?.name || '未提供'}`,
      candidates.length > 0 ? `可选候选：${candidates.join('、')}` : null,
      `触发动作：${request.pendingAction?.toolName || request.toolName || request.tool_name || '未提供'}`,
    ].filter((item): item is string => Boolean(item))
  }

  const payload = request?.payload || request?.arguments
  if (payload && typeof payload === 'object') {
    return Object.entries(payload).map(([key, value]) => `${key}：${String(value)}`)
  }
  return []
}

function statusBadgeProps(status: string): { color: string; label: string; variant?: 'light' } {
  if (status === 'approved') return { color: 'success', label: '已同意', variant: 'light' }
  if (status === 'rejected') return { color: 'danger', label: '已拒绝', variant: 'light' }
  if (status === 'failed') return { color: 'danger', label: '执行失败', variant: 'light' }
  if (status === 'processing') return { color: 'warning', label: '处理中', variant: 'light' }
  return { color: 'gray', label: '待确认', variant: 'light' }
}

export interface ConfirmCardProps {
  request: ConfirmRequest
  status: string
  errorMessage?: string
  onConfirm?: (request: ConfirmRequest) => void
  onReject?: (request: ConfirmRequest) => void
}

export default function ConfirmCard({ request, status, errorMessage = '', onConfirm, onReject }: ConfirmCardProps) {
  const details = getDetails(request)
  const badge = statusBadgeProps(status)
  const detailNodes: ReactNode[] = details.map((item, index) => (
    // details 为展示性文本行，以内容+序号作 key
    <Text
      key={`${index}-${item}`}
      fz="var(--text-xs)"
      c="dimmed"
      style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}
    >
      {item}
    </Text>
  ))

  return (
    <Paper w="100%" p="14px" radius="lg" bg="var(--color-warning-soft)" withBorder={false}>
      <Stack gap={6}>
        <Group justify="space-between" gap={8}>
          <Text fz="var(--text-xs)" c="warning.7" style={{ letterSpacing: '0.08em' }}>
            需要你确认
          </Text>
          <Badge {...badge} fz="var(--text-xs)">
            {badge.label}
          </Badge>
        </Group>

        <Text fz="var(--text-md)" fw={700} c="var(--color-text)">
          {getTitle(request)}
        </Text>

        <Text fz="var(--text-base)" c="warning.8" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>
          {getReason(request)}
        </Text>

        {details.length > 0 ? (
          <Stack gap={5} mt={4}>
            {detailNodes}
          </Stack>
        ) : null}

        {errorMessage ? (
          <Text fz="var(--text-xs)" c="danger.5" mt={4}>
            {errorMessage}
          </Text>
        ) : null}

        <Group gap={8} mt={6}>
          <Button
            type="button"
            style={{ flex: '1 1 0' }}
            disabled={status !== 'pending'}
            onClick={() => onConfirm?.(request)}
          >
            {status === 'processing' ? '处理中' : '同意'}
          </Button>
          <Button
            type="button"
            variant="subtle"
            style={{ flex: '1 1 0' }}
            disabled={status !== 'pending'}
            onClick={() => onReject?.(request)}
          >
            先不要
          </Button>
        </Group>
      </Stack>
    </Paper>
  )
}

// src/renderer/components/ConfirmCard.vue
<script setup>
import { computed } from 'vue'

const props = defineProps({
  request: {
    type: Object,
    default: () => ({}),
  },
  status: {
    type: String,
    default: 'pending',
  },
  errorMessage: {
    type: String,
    default: '',
  },
})

const emit = defineEmits(['confirm', 'reject'])

function getTitle(request) {
  if (request?.title) return request.title
  if (request?.kind === 'category_creation_confirmation') return '铃湾想先和你确认一下这个新类目'
  if (request?.kind === 'category_mapping_confirmation') return '铃湾想先确认要不要改用这个类目'
  if (request?.tool_name) return `这一步要不要继续处理 ${request.tool_name}？`
  if (request?.toolName) return `这一步要不要继续处理 ${request.toolName}？`
  return '这一步需要你点个头'
}

function getReason(request) {
  return request?.reason || '这件事继续做下去之前，铃湾想先征求你的同意。'
}

function getDetails(request) {
  if (Array.isArray(request?.details) && request.details.length > 0) {
    return request.details
  }

  if (request?.kind === 'category_creation_confirmation') {
    return [
      `所属领域：${request.domain || '未提供'}`,
      `建议类目：${request.proposedCategoryName || '未提供'}`,
      `触发动作：${request.pendingAction?.toolName || request.toolName || '未提供'}`,
    ]
  }

  if (request?.kind === 'category_mapping_confirmation') {
    const candidates = Array.isArray(request?.similarCandidates)
      ? request.similarCandidates.map((item) => item?.name).filter(Boolean)
      : []
    return [
      `所属领域：${request.domain || '未提供'}`,
      `推荐类目：${request.recommendedCategory?.name || '未提供'}`,
      candidates.length > 0 ? `可选候选：${candidates.join('、')}` : null,
      `触发动作：${request.pendingAction?.toolName || request.toolName || '未提供'}`,
    ].filter(Boolean)
  }

  const payload = request?.payload || request?.arguments
  if (payload && typeof payload === 'object') {
    return Object.entries(payload).map(([key, value]) => `${key}：${String(value)}`)
  }
  return []
}

const statusLabel = computed(() => {
  if (props.status === 'approved') return '你已经同意啦'
  if (props.status === 'rejected') return '这次先不做'
  if (props.status === 'failed') return '这次没继续成功'
  if (props.status === 'processing') return '铃湾正在继续处理'
  return '等你来决定'
})
</script>

<template>
  <div class="confirmCard">
    <div class="confirmTopline">
      <div class="confirmEyebrow">需要你点头</div>
      <div class="confirmStatusPill" :class="`is-${props.status || 'pending'}`">{{ statusLabel }}</div>
    </div>
    <div class="confirmTitle">{{ getTitle(props.request) }}</div>
    <div class="confirmReason">{{ getReason(props.request) }}</div>

    <div v-if="getDetails(props.request).length > 0" class="confirmDetails">
      <div v-for="item in getDetails(props.request)" :key="item" class="confirmDetail">{{ item }}</div>
    </div>

    <div v-if="props.errorMessage" class="confirmError">{{ props.errorMessage }}</div>
    <div v-if="props.status === 'approved'" class="confirmState">铃湾已经收到你的同意，正在继续做下去。</div>
    <div v-else-if="props.status === 'rejected'" class="confirmState">这次就先停在这里，不会继续执行。</div>
    <div v-else-if="props.status === 'failed'" class="confirmState">继续处理的时候出了点小岔子，可以稍后再试。</div>
    <div v-else-if="props.status === 'processing'" class="confirmState">铃湾正在顺着你的选择继续处理...</div>

    <div class="confirmActions">
      <button
        type="button"
        class="confirmBtn confirmBtnPrimary"
        :disabled="props.status !== 'pending'"
        @click="emit('confirm', props.request)"
      >
        {{ props.status === 'processing' ? '处理中' : '同意' }}
      </button>
      <button
        type="button"
        class="confirmBtn"
        :disabled="props.status !== 'pending'"
        @click="emit('reject', props.request)"
      >
        先不要
      </button>
    </div>
  </div>
</template>

<style scoped>
.confirmCard {
  width: 100%;
  padding: 14px;
  border-radius: 18px;
  border: 1px solid rgba(228, 163, 94, 0.24);
  background: var(--warning-soft);
}

.confirmTopline {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
}

.confirmEyebrow {
  font-size: 11px;
  letter-spacing: 0.08em;
  color: #b5783f;
}

.confirmStatusPill {
  padding: 3px 9px;
  border-radius: 999px;
  border: 1px solid rgba(0, 0, 0, 0.08);
  background: rgba(255, 255, 255, 0.72);
  color: var(--text);
  font-size: 10px;
  white-space: nowrap;
}

.confirmStatusPill.is-approved {
  border-color: rgba(91, 154, 107, 0.22);
  background: var(--success-soft);
  color: var(--success);
}

.confirmStatusPill.is-rejected,
.confirmStatusPill.is-failed {
  border-color: rgba(217, 106, 92, 0.2);
  background: var(--danger-soft);
  color: var(--danger);
}

.confirmStatusPill.is-processing {
  border-color: rgba(228, 163, 94, 0.24);
  background: rgba(255, 255, 255, 0.78);
  color: #9b6a36;
}

.confirmTitle {
  margin-top: 6px;
  font-size: 14px;
  font-weight: 700;
  color: var(--text);
}

.confirmReason {
  margin-top: 6px;
  font-size: 13px;
  line-height: 1.5;
  color: #6c5648;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

.confirmDetails {
  margin-top: 8px;
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.confirmDetail {
  font-size: 11px;
  color: var(--muted);
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

.confirmError {
  margin-top: 8px;
  font-size: 11px;
  color: var(--danger);
}

.confirmState {
  margin-top: 8px;
  font-size: 11px;
  color: #866955;
}

.confirmActions {
  margin-top: 10px;
  display: flex;
  gap: 8px;
}

.confirmBtn {
  flex: 1 1 0;
  height: 30px;
  border-radius: 999px;
  border: 1px solid rgba(0, 0, 0, 0.08);
  background: rgba(255, 255, 255, 0.72);
  color: var(--text);
  font-size: 12px;
  cursor: pointer;
}

.confirmBtnPrimary {
  border-color: rgba(228, 133, 106, 0.18);
  background: rgba(232, 133, 106, 0.16);
}

.confirmBtn:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}
</style>
