// src/renderer/components/ledger/LedgerCalendar.tsx
import { Month, type DayProps } from '@mantine/dates'
import { Box, Button, Group, Stack, Text } from '@mantine/core'

import { formatDate } from '../../utils/date'

// 记账月历（React 版 LedgerCalendar.vue）：
// 网格底座由 @mantine/dates Month 组件接管（旧版为手写 42 格），
// 周一起始（DatesProvider firstDayOfWeek=1）、今日/选中态、支出收入点标记经
// renderDay + getDateControlProps 注入，行为与旧版一致。
// 注：Mantine 9 的日期 API 以 'YYYY-MM-DD' 字符串传递。

export interface LedgerCalendarCell {
  date: string
  day: number
  inMonth: boolean
  expense: number
  income: number
}

export interface LedgerCalendarProps {
  month: Date
  cells: LedgerCalendarCell[]
  summaryByDay: Map<string, { expense: number; income: number }>
  selectedDate: string
  todayDate: string
  onPrevMonth: () => void
  onNextMonth: () => void
  onSelectDate: (date: string) => void
}

export default function LedgerCalendar({
  month,
  summaryByDay,
  selectedDate,
  todayDate,
  onPrevMonth,
  onNextMonth,
  onSelectDate,
}: LedgerCalendarProps) {
  const renderDay: DayProps['renderDay'] = (date) => {
    const key = String(date)
    const summary = summaryByDay.get(key)
    const hasExpense = (summary?.expense || 0) > 0
    const hasIncome = (summary?.income || 0) > 0
    const isToday = key === todayDate
    return (
      <Stack gap={2} align="center" justify="center">
        <Text
          fz="var(--text-base)"
          lh={1}
          style={isToday ? { color: 'var(--color-success)', fontWeight: 700 } : undefined}
        >
          {Number(key.slice(8, 10))}
        </Text>
        {hasExpense || hasIncome ? (
          <Group gap={4} wrap="nowrap">
            {hasExpense ? <Box w={6} h={6} style={{ borderRadius: 999, background: 'var(--color-danger)' }} /> : null}
            {hasIncome ? <Box w={6} h={6} style={{ borderRadius: 999, background: 'var(--color-success)' }} /> : null}
          </Group>
        ) : null}
      </Stack>
    )
  }

  return (
    <Box p="14px 16px" style={{ background: 'var(--color-surface)' }} className="card">
      <Group justify="space-between" gap={10}>
        <Button variant="subtle" size="compact-sm" style={{ borderRadius: 999 }} onClick={onPrevMonth}>
          上个月
        </Button>
        <Text fz="var(--text-md)" fw={700} c="var(--color-text)">
          {`${month.getFullYear()}年${month.getMonth() + 1}月`}
        </Text>
        <Button variant="subtle" size="compact-sm" style={{ borderRadius: 999 }} onClick={onNextMonth}>
          下个月
        </Button>
      </Group>

      <Month
        mt={12}
        month={formatDate(month)}
        firstDayOfWeek={1}
        renderDay={renderDay}
        getDayProps={(date) => {
          const key = String(date)
          return {
            selected: key === selectedDate && key !== todayDate,
            onClick: () => onSelectDate(key),
          }
        }}
        styles={{
          day: {
            minHeight: 46,
            borderRadius: 'var(--radius-lg)',
          },
        }}
      />
    </Box>
  )
}

// src/renderer/components/LedgerCalendar.vue
<script setup>
const props = defineProps({
  monthLabel: {
    type: String,
    default: '',
  },
  weekdayLabels: {
    type: Array,
    default: () => [],
  },
  cells: {
    type: Array,
    default: () => [],
  },
  selectedDate: {
    type: String,
    default: '',
  },
  todayDate: {
    type: String,
    default: '',
  },
})

const emit = defineEmits(['prev-month', 'next-month', 'select-date'])

function cellClasses(cell) {
  return {
    isMuted: !cell.inMonth,
    isToday: cell.date === props.todayDate,
    isSelected: cell.date === props.selectedDate,
    hasExpense: cell.expense > 0,
    hasIncome: cell.income > 0,
  }
}
</script>

<template>
  <div class="ledgerCalendar card">
    <div class="ledgerCalendarHead">
      <button class="ghost calendarNav" type="button" @click="emit('prev-month')">上个月</button>
      <div class="calendarTitle">{{ monthLabel }}</div>
      <button class="ghost calendarNav" type="button" @click="emit('next-month')">下个月</button>
    </div>

    <div class="calendarWeekdays">
      <div v-for="label in weekdayLabels" :key="label" class="calendarWeekday">{{ label }}</div>
    </div>

    <div class="calendarGrid">
      <button
        v-for="cell in cells"
        :key="cell.date"
        class="calendarCell"
        :class="cellClasses(cell)"
        type="button"
        @click="emit('select-date', cell.date)"
      >
        <span class="calendarDay">{{ cell.day }}</span>
        <span v-if="cell.expense > 0 || cell.income > 0" class="calendarDots">
          <span v-if="cell.expense > 0" class="calendarDot expense"></span>
          <span v-if="cell.income > 0" class="calendarDot income"></span>
        </span>
      </button>
    </div>
  </div>
</template>

<style scoped>
.ledgerCalendar {
  padding: 14px 16px;
  background: var(--color-surface);
}

.ledgerCalendarHead {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
}

.calendarTitle {
  font-size: var(--text-md);
  font-weight: 700;
  color: var(--text);
}

.calendarNav {
  padding: 6px 10px;
  border-radius: 999px;
  color: var(--muted);
}

.calendarWeekdays {
  margin-top: 12px;
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 6px;
}

.calendarWeekday {
  text-align: center;
  font-size: var(--text-xs);
  color: var(--muted);
}

.calendarGrid {
  margin-top: 8px;
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 6px;
}

.calendarCell {
  min-height: 46px;
  border: none;
  border-radius: 14px;
  background: transparent;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 4px;
  padding: 6px 0;
  color: var(--text);
}

.calendarCell:hover {
  background: color-mix(in srgb, var(--color-text) 4%, transparent);
}

.calendarCell.isMuted {
  color: color-mix(in srgb, var(--color-text) 35%, transparent);
}

.calendarCell.isToday {
  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--color-success) 22%, transparent);
  background: color-mix(in srgb, var(--color-success) 7%, transparent);
}

.calendarCell.isSelected {
  background: var(--success-soft);
  color: var(--text);
}

.calendarDay {
  font-size: var(--text-base);
  line-height: 1;
}

.calendarDots {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}

.calendarDot {
  width: 6px;
  height: 6px;
  border-radius: 999px;
}

.calendarDot.expense {
  background: var(--danger);
}

.calendarDot.income {
  background: var(--success);
}
</style>
