// src/renderer/pages/OnThisDayPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Box, Button, Card, EmptyState, Grid, Stack, Text } from '@mantine/core'
import { IconCalendarOff } from '@tabler/icons-react'

import { listOnThisDay } from '../api'
import CornieDiaryMarkdown from '../components/diary/CornieDiaryMarkdown'
import { today } from '../utils/date'

// 往年今日页（React 版 OnThisDayPage.vue）：按今天日期回看往年同日的日记。

interface OtdItem {
  date?: string
  userText?: string
  cornieText?: string
  [key: string]: unknown
}

export default function OnThisDayPage() {
  const navigate = useNavigate()
  const [date] = useState(() => today())
  const [items, setItems] = useState<OtdItem[]>([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    let cancelled = false
    const init = async () => {
      setLoading(true)
      try {
        const data = (await listOnThisDay(date, { limit: 20 })) as { items?: OtdItem[] }
        if (!cancelled) setItems(data.items || [])
      } catch {
        /* ignore */
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    void init()
    return () => {
      cancelled = true
    }
  }, [date])

  return (
    <Stack gap={14} h="100%" style={{ overflow: 'hidden' }}>
      <Button variant="subtle" w="fit-content" onClick={() => navigate('/diary')}>
        ← 返回日记首页
      </Button>

      <Text ta="center" fz="var(--text-2xl)" fw={800}>
        往年今日
      </Text>

      {loading ? (
        <Text ta="center" c="dimmed" py={40}>
          加载中…
        </Text>
      ) : items.length === 0 ? (
        <EmptyState icon={<IconCalendarOff size={32} stroke={1.5} />} title="暂无记录" mih={240} />
      ) : (
        <Stack gap={12} style={{ flex: 1, overflowY: 'auto', paddingRight: 2, minHeight: 0 }}>
          {items.map((it) => (
            <Card key={String(it.date)} p={16} withBorder>
              <Text fw={700} mb={10}>
                {it.date}
              </Text>
              <Grid gap={14}>
                <Grid.Col span={{ base: 12, md: 6 }}>
                  <Text fz="var(--text-sm)" c="dimmed" mb={4}>
                    我的日记
                  </Text>
                  <Box
                    fz="var(--text-md)"
                    style={{ whiteSpace: 'pre-wrap', lineHeight: 1.5, maxHeight: 240, overflowY: 'auto' }}
                  >
                    {it.userText || '（空）'}
                  </Box>
                </Grid.Col>
                <Grid.Col span={{ base: 12, md: 6 }}>
                  <Text fz="var(--text-sm)" c="dimmed" mb={4}>
                    Cornie 日记
                  </Text>
                  {it.cornieText ? (
                    <Box fz="var(--text-md)" style={{ maxHeight: 240, overflowY: 'auto', color: 'brand.8' }}>
                      <CornieDiaryMarkdown content={it.cornieText} />
                    </Box>
                  ) : (
                    <Text fz="var(--text-md)">（空）</Text>
                  )}
                </Grid.Col>
              </Grid>
            </Card>
          ))}
        </Stack>
      )}
    </Stack>
  )
}

// src/renderer/components/OnThisDayPage.vue
<script setup>
import { onMounted, ref } from 'vue'
import { listOnThisDay } from '../api'
import CornieDiaryMarkdown from './CornieDiaryMarkdown.vue'
import UiButton from './ui/UiButton.vue'
import UiCard from './ui/UiCard.vue'
import UiEmpty from './ui/UiEmpty.vue'

function pad2(n) {
  return String(n).padStart(2, '0')
}
function toISODate(d) {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`
}

const date = ref(toISODate(new Date()))
const items = ref([])
const loading = ref(false)

onMounted(async () => {
  loading.value = true
  try {
    const data = await listOnThisDay(date.value, { limit: 20 })
    items.value = data.items || []
  } catch {
    /* ignore */
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <div class="otdPage">
    <UiButton variant="ghost" class="backBtn" @click="$emit('back')">← 返回日记首页</UiButton>

    <div class="otdHeader">
      <div class="otdTitle">往年今日</div>
    </div>

    <div v-if="loading" class="otdStatus">加载中…</div>
    <UiEmpty v-else-if="items.length === 0" icon="📅" text="暂无记录" />
    <div v-else class="otdGrid">
      <UiCard v-for="it in items" :key="it.date" class="otdCard">
        <div class="otdDate">{{ it.date }}</div>
        <div class="otdCols">
          <div class="otdCol">
            <div class="otdLabel">我的日记</div>
            <div class="otdText">{{ it.userText || '（空）' }}</div>
          </div>
          <div class="otdCol">
            <div class="otdLabel">Cornie 日记</div>
            <div v-if="it.cornieText" class="otdText cornieText">
              <CornieDiaryMarkdown :content="it.cornieText" />
            </div>
            <div v-else class="otdText">（空）</div>
          </div>
        </div>
      </UiCard>
    </div>
  </div>
</template>

<style scoped>
.otdPage {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 14px;
  overflow: hidden;
}
.backBtn {
  align-self: flex-start;
}

.otdHeader {
  padding: 4px 0 0 0;
  text-align: center;
}
.otdTitle {
  font-size: var(--text-2xl);
  font-weight: 800;
}

.otdStatus {
  text-align: center;
  color: var(--muted);
  padding: 40px;
}

.otdGrid {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding-right: 2px;
}
.otdGrid::-webkit-scrollbar {
  width: 4px;
}
.otdGrid::-webkit-scrollbar-thumb {
  background: color-mix(in srgb, var(--color-text) 8%, transparent);
  border-radius: 999px;
}

.otdCard {
  padding: 16px;
}
.otdDate {
  font-weight: 700;
  margin-bottom: 10px;
}
.otdCols {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14px;
}
.otdLabel {
  font-size: var(--text-sm);
  color: var(--muted);
  margin-bottom: 4px;
}
.otdText {
  white-space: pre-wrap;
  line-height: 1.5;
  font-size: var(--text-md);
  max-height: 240px;
  overflow-y: auto;
}
.cornieText {
  white-space: normal;
  color: color-mix(in srgb, var(--color-accent) 45%, var(--color-text));
}
:deep(.cornieText .cornieMarkdown) {
  gap: 8px;
}
:deep(.cornieText .mdParagraph),
:deep(.cornieText .mdQuote),
:deep(.cornieText .mdList) {
  font-size: var(--text-md);
}

@media (max-width: 760px) {
  .otdCols {
    grid-template-columns: 1fr;
  }
}
</style>
