// src/renderer/components/MemoryWikiPageListPanel.vue
<script setup>
import UiCard from './ui/UiCard.vue'
import UiEmpty from './ui/UiEmpty.vue'

defineProps({
  pages: { type: Array, default: () => [] },
  selectedPageId: { type: String, default: '' },
  filterType: { type: String, default: '' },
  filterStatus: { type: String, default: '' },
})

const emit = defineEmits(['select-page', 'change', 'update:filterType', 'update:filterStatus'])

function handleTypeChange(event) {
  emit('update:filterType', event.target.value)
  emit('change')
}

function handleStatusChange(event) {
  emit('update:filterStatus', event.target.value)
  emit('change')
}
</script>

<template>
  <UiCard title="记忆页面">
    <template #actions>
      <div class="cardFilters">
        <select :value="filterType" @change="handleTypeChange">
          <option value="">全部类型</option>
          <option value="topic">topic</option>
          <option value="person">person</option>
          <option value="event">event</option>
          <option value="preference">preference</option>
          <option value="identity_profile">identity_profile</option>
          <option value="identity_person">identity_person</option>
          <option value="identity_preference">identity_preference</option>
          <option value="identity_trait">identity_trait</option>
        </select>
        <select :value="filterStatus" @change="handleStatusChange">
          <option value="">全部状态</option>
          <option value="active">active</option>
          <option value="inactive">inactive</option>
          <option value="archived">archived</option>
        </select>
      </div>
    </template>

    <UiEmpty v-if="pages.length === 0" icon="📄" text="暂无记忆页面" />

    <div v-else class="entryList">
      <button
        v-for="page in pages"
        :key="page.pageId"
        class="entryRow"
        :class="{ active: page.pageId === selectedPageId }"
        @click="emit('select-page', page.pageId)"
      >
        <div>
          <div class="entryMain">{{ page.title }}</div>
          <div class="entryMeta">{{ page.pageType }} · {{ page.status }} · {{ page.importance }}</div>
        </div>
      </button>
    </div>
  </UiCard>
</template>

<style scoped>
.cardFilters {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}
.entryList {
  display: flex;
  flex-direction: column;
  gap: 8px;
  overflow: auto;
}
.entryRow {
  text-align: left;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 12px 14px;
  border-radius: 16px;
}
.entryRow.active {
  background: color-mix(in srgb, var(--color-accent) 10%, transparent);
}
.entryMain {
  font-weight: 700;
}
.entryMeta {
  margin-top: 4px;
  font-size: var(--text-sm);
  color: var(--muted);
}
</style>

// src/renderer/components/memory/MemoryWikiPageListPanel.tsx
// 页面列表卡（React 版 components/MemoryWikiPageListPanel.vue）：类型/状态筛选 + 页面行 + 空态。
import { Badge, Box, Card, EmptyState, Group, Select, Stack, Text, UnstyledButton } from '@mantine/core'
import { IconFileText } from '@tabler/icons-react'

import type { MemoryWikiPage } from '../../api'
import { MEMORY_PAGE_STATUS_OPTIONS, MEMORY_PAGE_TYPE_OPTIONS } from '../../hooks/useMemoryWikiWorkspace'

const TYPE_SELECT_DATA = [
  { value: '', label: '全部类型' },
  ...MEMORY_PAGE_TYPE_OPTIONS.map((value) => ({ value, label: value })),
]

const STATUS_SELECT_DATA = [
  { value: '', label: '全部状态' },
  ...MEMORY_PAGE_STATUS_OPTIONS.map((value) => ({ value, label: value })),
]

interface MemoryWikiPageListPanelProps {
  pages: MemoryWikiPage[]
  selectedPageId: string
  filterType: string
  filterStatus: string
  onSelectPage: (pageId: string) => void
  onFilterTypeChange: (value: string) => void
  onFilterStatusChange: (value: string) => void
}

export default function MemoryWikiPageListPanel({
  pages,
  selectedPageId,
  filterType,
  filterStatus,
  onSelectPage,
  onFilterTypeChange,
  onFilterStatusChange,
}: MemoryWikiPageListPanelProps) {
  return (
    <Card p="16px" withBorder style={{ display: 'flex', flexDirection: 'column', gap: 12, minHeight: 0 }}>
      <Group justify="space-between" align="flex-start" gap={8} wrap="wrap">
        <Text fw={700}>记忆页面</Text>
        <Group gap={8} wrap="wrap">
          <Select
            w={150}
            size="sm"
            allowDeselect={false}
            data={TYPE_SELECT_DATA}
            value={filterType}
            onChange={(value) => onFilterTypeChange(value || '')}
          />
          <Select
            w={140}
            size="sm"
            allowDeselect={false}
            data={STATUS_SELECT_DATA}
            value={filterStatus}
            onChange={(value) => onFilterStatusChange(value || '')}
          />
        </Group>
      </Group>

      {pages.length === 0 ? (
        <EmptyState size="sm" icon={<IconFileText size={24} stroke={1.5} />} title="暂无记忆页面" />
      ) : (
        <Stack gap={8} style={{ overflowY: 'auto', minHeight: 0 }}>
          {pages.map((page) => {
            const active = page.pageId === selectedPageId
            return (
              <UnstyledButton
                key={page.pageId}
                onClick={() => onSelectPage(page.pageId)}
                px={14}
                py={12}
                w="100%"
                bg={active ? 'var(--color-tint-memory)' : 'transparent'}
                style={{ borderRadius: 'var(--radius-lg)', textAlign: 'left' }}
              >
                <Group justify="space-between" gap={12} wrap="nowrap">
                  <Box style={{ minWidth: 0 }}>
                    <Text fw={700} truncate>
                      {page.title || page.pageId}
                    </Text>
                    <Text fz="var(--text-sm)" c="dimmed" mt={4} truncate>
                      {page.pageType ?? 'unknown'} · {page.status ?? 'unknown'} · {String(page.importance ?? 'unknown')}
                    </Text>
                  </Box>
                  {active ? (
                    <Badge size="sm" variant="light" color="brand" style={{ flex: '0 0 auto' }}>
                      当前
                    </Badge>
                  ) : null}
                </Group>
              </UnstyledButton>
            )
          })}
        </Stack>
      )}
    </Card>
  )
}
