// src/renderer/components/MemoryWikiGovernanceQueuePanel.vue
<script setup>
import UiCard from './ui/UiCard.vue'
import UiEmpty from './ui/UiEmpty.vue'

defineProps({
  governanceItems: { type: Array, default: () => [] },
  selectedGovernanceId: { type: String, default: '' },
  filterStatus: { type: String, default: 'pending' },
  filterSection: { type: String, default: '' },
  sections: { type: Array, default: () => [] },
  pendingCount: { type: Number, default: 0 },
  filterSummary: { type: String, default: '' },
})

const emit = defineEmits(['select-governance', 'change', 'update:filterStatus', 'update:filterSection'])

function handleStatusChange(event) {
  emit('update:filterStatus', event.target.value)
  emit('change')
}

function handleSectionChange(event) {
  emit('update:filterSection', event.target.value)
  emit('change')
}
</script>

<template>
  <UiCard title="治理待审核区">
    <template #actions>
      <div class="cardFilters">
        <select :value="filterStatus" @change="handleStatusChange">
          <option value="">全部状态</option>
          <option value="pending">pending</option>
          <option value="approved">approved</option>
          <option value="rejected">rejected</option>
          <option value="deferred">deferred</option>
        </select>
        <select :value="filterSection" @change="handleSectionChange">
          <option value="">全部分区</option>
          <option v-for="section in sections" :key="section" :value="section">{{ section }}</option>
        </select>
      </div>
    </template>

    <div class="queueSummary">
      当前待处理 <strong>{{ pendingCount }}</strong> 项
    </div>

    <div class="filterSummary">当前筛选：{{ filterSummary }}</div>

    <UiEmpty v-if="governanceItems.length === 0" icon="🧭" text="暂无治理建议" />

    <div v-else class="entryList">
      <button
        v-for="item in governanceItems"
        :key="item.requestId"
        class="entryRow"
        :class="{ active: item.requestId === selectedGovernanceId }"
        @click="emit('select-governance', item.requestId)"
      >
        <div>
          <div class="entryMain">{{ item.title || item.requestType }}</div>
          <div class="entryMeta">{{ item.queueSection }} · {{ item.status }} · {{ item.riskLevel }}</div>
        </div>
      </button>
    </div>
  </UiCard>
</template>

<style scoped>
.cardFilters {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}
.queueSummary {
  padding: 12px 14px;
  border-radius: 14px;
  background: var(--surface-2);
  color: var(--muted);
  font-size: var(--text-base);
}
.filterSummary {
  padding: 12px 14px;
  border-radius: 14px;
  background: var(--color-info-soft);
  color: var(--text);
  font-size: var(--text-base);
}
.entryList {
  display: flex;
  flex-direction: column;
  gap: 8px;
  overflow: auto;
}
.entryRow {
  text-align: left;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 12px 14px;
  border-radius: 16px;
}
.entryRow.active {
  background: color-mix(in srgb, var(--color-accent) 10%, transparent);
}
.entryMain {
  font-weight: 700;
}
.entryMeta {
  margin-top: 4px;
  font-size: var(--text-sm);
  color: var(--muted);
}
</style>

// src/renderer/components/memory/MemoryWikiGovernanceQueuePanel.tsx
// 治理队列卡（React 版 components/MemoryWikiGovernanceQueuePanel.vue）：
// 状态/分区两个筛选（分区选项来自现有 items 的 queueSection 去重）+ 待处理计数 + 筛选摘要 + 请求行。
import { Card, EmptyState, Group, Paper, Select, Stack, Text, UnstyledButton } from '@mantine/core'
import { IconCompass } from '@tabler/icons-react'

import type { GovernanceQueueItem } from '../../hooks/useMemoryWikiWorkspace'

const STATUS_SELECT_DATA = [
  { value: '', label: '全部状态' },
  { value: 'pending', label: 'pending' },
  { value: 'approved', label: 'approved' },
  { value: 'rejected', label: 'rejected' },
  { value: 'deferred', label: 'deferred' },
]

interface MemoryWikiGovernanceQueuePanelProps {
  governanceItems: GovernanceQueueItem[]
  selectedGovernanceId: string
  filterStatus: string
  filterSection: string
  sections: string[]
  pendingCount: number
  filterSummary: string
  onSelectGovernance: (requestId: string) => void
  onFilterStatusChange: (value: string) => void
  onFilterSectionChange: (value: string) => void
}

export default function MemoryWikiGovernanceQueuePanel({
  governanceItems,
  selectedGovernanceId,
  filterStatus,
  filterSection,
  sections,
  pendingCount,
  filterSummary,
  onSelectGovernance,
  onFilterStatusChange,
  onFilterSectionChange,
}: MemoryWikiGovernanceQueuePanelProps) {
  return (
    <Card p="16px" withBorder style={{ display: 'flex', flexDirection: 'column', gap: 12, minHeight: 0 }}>
      <Group justify="space-between" align="flex-start" gap={8} wrap="wrap">
        <Text fw={700}>治理待审核区</Text>
        <Group gap={8} wrap="wrap">
          <Select
            w={140}
            size="sm"
            allowDeselect={false}
            data={STATUS_SELECT_DATA}
            value={filterStatus}
            onChange={(value) => onFilterStatusChange(value || '')}
          />
          <Select
            w={140}
            size="sm"
            allowDeselect={false}
            data={[
              { value: '', label: '全部分区' },
              ...sections.map((section) => ({ value: section, label: section })),
            ]}
            value={filterSection}
            onChange={(value) => onFilterSectionChange(value || '')}
          />
        </Group>
      </Group>

      <Paper px={14} py={12} radius="md" bg="var(--color-surface-2)">
        <Text fz="var(--text-base)" c="dimmed">
          当前待处理{' '}
          <Text component="span" fw={700} c="var(--color-text)">
            {pendingCount}
          </Text>{' '}
          项
        </Text>
      </Paper>

      <Paper px={14} py={12} radius="md" bg="var(--color-info-soft)">
        <Text fz="var(--text-base)">当前筛选：{filterSummary}</Text>
      </Paper>

      {governanceItems.length === 0 ? (
        <EmptyState size="sm" icon={<IconCompass size={24} stroke={1.5} />} title="暂无治理建议" />
      ) : (
        <Stack gap={8} style={{ overflowY: 'auto', minHeight: 0 }}>
          {governanceItems.map((item) => {
            const active = item.requestId === selectedGovernanceId
            return (
              <UnstyledButton
                key={item.requestId}
                onClick={() => onSelectGovernance(item.requestId)}
                px={14}
                py={12}
                w="100%"
                bg={active ? 'var(--color-tint-memory)' : 'transparent'}
                style={{ borderRadius: 'var(--radius-lg)', textAlign: 'left' }}
              >
                <Text fw={700} truncate>
                  {item.title || item.requestType || item.requestId}
                </Text>
                <Text fz="var(--text-sm)" c="dimmed" mt={4} truncate>
                  {item.queueSection ?? 'unknown'} · {item.status ?? 'unknown'} · {item.riskLevel ?? 'unknown'}
                </Text>
              </UnstyledButton>
            )
          })}
        </Stack>
      )}
    </Card>
  )
}
