// src/renderer/components/MemoryWikiWorkspaceHead.vue
<script setup>
defineProps({
  loading: { type: Boolean, default: false },
  saving: { type: Boolean, default: false }
})

const emit = defineEmits(['run-inspection', 'refresh'])
</script>

<template>
  <header class="workspaceHead">
    <div>
      <div class="workspaceTitle">Memory Wiki 工作台</div>
    </div>
    <div class="headActions">
      <button :disabled="saving" @click="emit('run-inspection')">
        {{ saving ? '处理中…' : '运行巡检入池' }}
      </button>
      <button :disabled="loading" @click="emit('refresh')">
        {{ loading ? '刷新中…' : '刷新全部' }}
      </button>
    </div>
  </header>
</template>

<style scoped>
.workspaceHead{
  display:flex;
  justify-content: space-between;
  align-items:flex-start;
  gap: 12px;
}
.workspaceTitle{ font-size: 22px; font-weight: 800; }
.workspaceHint{ margin-top: 6px; color: var(--muted); font-size: 13px; line-height: 1.5; max-width: 720px; }
.headActions{
  display:flex;
  gap: 10px;
  flex-wrap: wrap;
}
@media (max-width: 720px){
  .workspaceHead{
    flex-direction: column;
  }
}
</style>

// src/renderer/components/memory/MemoryWikiWorkspaceHead.tsx
// 工作台头（React 版 components/MemoryWikiWorkspaceHead.vue）：标题 +「运行巡检入池」「刷新全部」。
import { Button, Group, Text } from '@mantine/core'
import { IconRadar, IconRefresh } from '@tabler/icons-react'

interface MemoryWikiWorkspaceHeadProps {
  loading: boolean
  saving: boolean
  onRunInspection: () => void
  onRefresh: () => void
}

export default function MemoryWikiWorkspaceHead({
  loading,
  saving,
  onRunInspection,
  onRefresh,
}: MemoryWikiWorkspaceHeadProps) {
  return (
    <Group justify="space-between" align="flex-start" gap={12} wrap="wrap">
      <Text fz="var(--text-2xl)" fw={800}>
        Memory Wiki 工作台
      </Text>
      <Group gap={10} wrap="wrap">
        <Button leftSection={<IconRadar size={16} stroke={1.8} />} disabled={saving} onClick={onRunInspection}>
          {saving ? '处理中…' : '运行巡检入池'}
        </Button>
        <Button
          variant="default"
          leftSection={<IconRefresh size={16} stroke={1.8} />}
          disabled={loading}
          onClick={onRefresh}
        >
          {loading ? '刷新中…' : '刷新全部'}
        </Button>
      </Group>
    </Group>
  )
}
