// src/renderer/components/ChatHome.vue
<script setup>
import { computed, nextTick, onMounted, onBeforeUnmount, ref, watch } from 'vue'
import { useChat } from '../composables/useChat'
import { today } from '../utils/date'
import UiButton from './ui/UiButton.vue'
import UiEmpty from './ui/UiEmpty.vue'
import ConfirmCard from './ConfirmCard.vue'
import AskBackBubble from './AskBackBubble.vue'
import ToolResultPanel from './ToolResultPanel.vue'

const {
  messages,
  sending,
  streamSend,
  handleConfirmAction,
  restorePendingConfirmations,
  loadConversation,
  startConversationSync,
  stopConversationSync,
} = useChat()

const message = ref('')
const chatListRef = ref(null)
const isPinnedToBottom = ref(true)
const hasUnreadBelow = ref(false)
const hasInitializedScroll = ref(false)
const autoStickThreshold = 36

const todayDate = computed(() => {
  const d = new Date()
  const weekDay = ['日', '一', '二', '三', '四', '五', '六'][d.getDay()]
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 星期${weekDay}`
})

const greeting = computed(() => {
  const h = new Date().getHours()
  if (h < 6) return '夜深了，还没睡吗？'
  if (h < 12) return '早上好，今天是个新开始。'
  if (h < 14) return '中午好，记得吃午饭呀。'
  if (h < 18) return '下午好，今天过得怎么样？'
  return '晚上好，今天辛苦啦。'
})

const pendingCount = computed(() => messages.value.filter((m) => m.kind === 'confirm' && m.status === 'pending').length)

defineEmits(['go-history'])

function getDistanceFromBottom(el) {
  return el.scrollHeight - el.scrollTop - el.clientHeight
}

function isNearBottom(el) {
  return getDistanceFromBottom(el) <= autoStickThreshold
}

function updatePinnedState() {
  const el = chatListRef.value
  if (!el) return
  const pinned = isNearBottom(el)
  isPinnedToBottom.value = pinned
  if (pinned) {
    hasUnreadBelow.value = false
  }
}

function handleChatScroll() {
  updatePinnedState()
}

async function scrollToBottom(force = false) {
  await nextTick()
  const el = chatListRef.value
  if (!el) return
  if (!force && !isPinnedToBottom.value) {
    hasUnreadBelow.value = true
    return
  }
  el.scrollTop = el.scrollHeight
  isPinnedToBottom.value = true
  hasUnreadBelow.value = false
}

async function onSend() {
  const text = message.value.trim()
  if (!text || sending.value) return
  message.value = ''
  // FE-03：主聊天入口默认流式；非流式 send 保留为回退（sendFallback，当前未被 UI 使用）。
  await streamSend(text)
  await scrollToBottom()
}

function autoResize(e) {
  const el = e.target
  el.style.height = 'auto'
  el.style.height = Math.min(el.scrollHeight, 120) + 'px'
}

async function onConfirm(action, item) {
  await handleConfirmAction(action, item)
  await scrollToBottom()
}

async function jumpToBottom() {
  await scrollToBottom(true)
}

onMounted(async () => {
  const date = today()
  await loadConversation(date)
  await restorePendingConfirmations(date)
  await scrollToBottom(true)
  hasInitializedScroll.value = true
  startConversationSync(date, {
    onAfterSync: async () => {
      await scrollToBottom()
    },
  })
})

onBeforeUnmount(() => {
  stopConversationSync()
})

watch(
  () => messages.value.length,
  async (current, previous) => {
    if (!hasInitializedScroll.value || current <= previous) return
    await scrollToBottom()
  }
)
</script>

<template>
  <div class="chatPage">
    <!-- 顶部陪伴区 -->
    <div class="chatCompanion">
      <span class="chatGreeting">{{ greeting }}</span>
      <span class="chatDate">{{ todayDate }}</span>
      <UiButton variant="ghost" class="chatHistoryBtn" type="button" @click="$emit('go-history')"
        >翻看以前聊天</UiButton
      >
      <span class="chatTagline">想和我聊点什么？</span>
    </div>

    <!-- 主对话区 -->
    <div class="chatMessages" ref="chatListRef" @scroll="handleChatScroll">
      <div v-if="messages.length === 0 && !sending" class="chatEmpty">
        <UiEmpty icon="💬" text="给铃湾发一条消息吧" />
      </div>

      <div v-else class="chatList">
        <div
          v-for="m in messages"
          :key="m.id"
          class="chatItem"
          :class="[m.kind === 'message' && m.role === 'user' ? 'chatItemUser' : 'chatItemCornie']"
        >
          <template v-if="m.kind === 'message'">
            <div class="bubble" :class="m.role === 'user' ? 'bubbleUser' : 'bubbleCornie'">
              <div class="bubbleRole">{{ m.role === 'user' ? '你' : '铃湾' }}</div>
              <div class="bubbleText">{{ m.content }}</div>
            </div>
          </template>

          <template v-else-if="m.kind === 'tool_result'">
            <ToolResultPanel :results="m.results" />
          </template>

          <template v-else-if="m.kind === 'confirm'">
            <ConfirmCard
              :request="m.request"
              :status="m.status || 'pending'"
              :error-message="m.errorMessage || ''"
              @confirm="onConfirm('confirm', m)"
              @reject="onConfirm('reject', m)"
            />
          </template>

          <template v-else-if="m.kind === 'ask_back'">
            <AskBackBubble :question="m.question" :reason="m.reason" />
          </template>

          <template v-else-if="m.kind === 'error'">
            <div class="bubble bubbleError">
              <div class="bubbleRole">系统提示</div>
              <div class="bubbleText">{{ m.content }}</div>
            </div>
          </template>
        </div>

        <div v-if="sending" class="bubble bubbleCornie">
          <div class="bubbleRole">铃湾</div>
          <div class="bubbleText thinking">正在思考...</div>
        </div>
      </div>

      <UiButton v-if="hasUnreadBelow" variant="secondary" class="chatJumpBottom" type="button" @click="jumpToBottom">
        回到底部
      </UiButton>
    </div>

    <!-- 输入区 -->
    <div class="chatInputBar">
      <textarea
        v-model="message"
        class="chatTextarea"
        placeholder="和铃湾说句话..."
        rows="1"
        @keydown.enter.exact.prevent="onSend"
        @input="autoResize"
      />
      <UiButton variant="default" class="chatSendBtn" :disabled="!message.trim() || sending" @click="onSend">
        发送
      </UiButton>
    </div>

    <!-- 待确认提示 -->
    <div v-if="pendingCount > 0" class="chatPendingHint">有 {{ pendingCount }} 条待确认事项，请在上面处理。</div>
  </div>
</template>

<style scoped>
.chatPage {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 0;
  background: var(--surface);
  border-radius: var(--radius-lg);
  overflow: hidden;
}

/* ─── 顶部陪伴区（压缩为一行） ─── */
.chatCompanion {
  display: flex;
  align-items: baseline;
  gap: 12px;
  padding: 8px 20px;
  border-bottom: 1px solid var(--border);
  background: var(--chat-tint);
  flex: 0 0 auto;
}
.chatGreeting {
  font-size: var(--text-md);
  font-weight: 700;
  color: var(--text);
  white-space: nowrap;
}
.chatDate {
  font-size: var(--text-sm);
  color: var(--muted);
}
.chatHistoryBtn {
  padding: 6px 10px;
  margin-left: 6px;
}
.chatTagline {
  margin-left: auto;
  font-size: var(--text-sm);
  color: var(--muted);
}

/* ─── 主对话区 ─── */
.chatMessages {
  flex: 1;
  overflow-y: auto;
  padding: 14px 20px;
  scroll-behavior: smooth;
  position: relative;
}
.chatMessages::-webkit-scrollbar {
  width: 4px;
}
.chatMessages::-webkit-scrollbar-thumb {
  background: color-mix(in srgb, var(--color-text) 10%, transparent);
  border-radius: 999px;
}

.chatEmpty {
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  color: var(--muted);
}

.chatList {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.chatItem {
  width: 100%;
  display: flex;
}
.chatItemUser {
  justify-content: flex-end;
}
.chatItemCornie {
  justify-content: flex-start;
}

/* ─── 气泡 ─── */
.bubble {
  max-width: 75%;
  padding: 8px 14px;
  border-radius: var(--radius-lg);
  font-size: var(--text-md);
  line-height: 1.6;
}
.bubbleUser {
  background: var(--accent);
  color: var(--color-surface);
  border-bottom-right-radius: 6px;
}
.bubbleCornie {
  background: var(--surface-2);
  color: var(--text);
  border-bottom-left-radius: 6px;
}
.bubbleError {
  max-width: 100%;
  background: color-mix(in srgb, var(--color-danger) 8%, transparent);
  color: var(--danger);
}
.bubbleRole {
  font-size: var(--text-xs);
  opacity: 0.6;
  margin-bottom: 2px;
}
.bubbleText {
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
.bubbleText.thinking {
  font-style: italic;
  opacity: 0.6;
}

.chatJumpBottom {
  position: sticky;
  left: 100%;
  bottom: 10px;
  margin-top: 12px;
  margin-left: auto;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.chatJumpBottom:hover {
  background: var(--color-surface);
}

/* ─── 输入区 ─── */
.chatInputBar {
  display: flex;
  align-items: flex-end;
  gap: 8px;
  padding: 10px 16px;
  border-top: 1px solid var(--border);
  background: var(--surface);
}
.chatTextarea {
  flex: 1;
  min-height: 36px;
  max-height: 120px;
  resize: none;
  border-radius: var(--radius-md);
  padding: 8px 14px;
  font-size: var(--text-md);
  line-height: 1.5;
  background: var(--bg);
  color: var(--text);
  outline: none;
}
.chatTextarea:focus {
  border-color: var(--accent);
}
.chatTextarea::placeholder {
  color: var(--muted);
}
.chatSendBtn {
  flex: 0 0 auto;
  white-space: nowrap;
}

/* ─── 待确认提示 ─── */
.chatPendingHint {
  padding: 6px 20px;
  text-align: center;
  font-size: var(--text-sm);
  color: var(--muted);
  background: var(--chat-tint);
  border-top: 1px solid var(--border);
}
</style>

// src/renderer/pages/ChatHome.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Box, Button, EmptyState, Group, Stack, Text, Textarea } from '@mantine/core'
import { IconMessageCircle } from '@tabler/icons-react'

import { useChat, type ChatConfirmItem, type ChatItem } from '../hooks/useChat'
import { today } from '../utils/date'
import ConfirmCard from '../components/chat/ConfirmCard'
import AskBackBubble from '../components/chat/AskBackBubble'
import ToolResultPanel from '../components/chat/ToolResultPanel'

// 主聊天页（React 版 ChatHome.vue）：FE-03 流式发送 + R-02 消息 reconcile + FE-04 轮询同步。
// 交互契约：底部吸附（36px 阈值）、离底未读提示、Enter 发送/Shift+Enter 换行、
// 输入框自增高（maxHeight 120px）、待确认提示条。导航由 useNavigate 完成（go-history）。

const AUTO_STICK_THRESHOLD = 36

function getDistanceFromBottom(el: HTMLElement): number {
  return el.scrollHeight - el.scrollTop - el.clientHeight
}

function isNearBottom(el: HTMLElement): boolean {
  return getDistanceFromBottom(el) <= AUTO_STICK_THRESHOLD
}

export default function ChatHome() {
  const navigate = useNavigate()
  const {
    messages,
    sending,
    streamSend,
    handleConfirmAction,
    restorePendingConfirmations,
    loadConversation,
    startConversationSync,
  } = useChat()

  const [message, setMessage] = useState('')
  const chatListRef = useRef<HTMLDivElement | null>(null)
  const pinnedRef = useRef(true)
  const [hasUnreadBelow, setHasUnreadBelow] = useState(false)
  const hasInitializedScrollRef = useRef(false)
  const prevMessageCountRef = useRef(0)

  const todayDate = useMemo(() => {
    const d = new Date()
    const weekDay = ['日', '一', '二', '三', '四', '五', '六'][d.getDay()]
    return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 星期${weekDay}`
  }, [])

  const greeting = useMemo(() => {
    const h = new Date().getHours()
    if (h < 6) return '夜深了，还没睡吗？'
    if (h < 12) return '早上好，今天是个新开始。'
    if (h < 14) return '中午好，记得吃午饭呀。'
    if (h < 18) return '下午好，今天过得怎么样？'
    return '晚上好，今天辛苦啦。'
  }, [])

  const pendingCount = useMemo(
    () => messages.filter((m) => m.kind === 'confirm' && m.status === 'pending').length,
    [messages]
  )

  const scrollToBottom = useCallback((force = false) => {
    const el = chatListRef.current
    if (!el) return
    if (!force && !pinnedRef.current) {
      setHasUnreadBelow(true)
      return
    }
    el.scrollTop = el.scrollHeight
    pinnedRef.current = true
    setHasUnreadBelow(false)
  }, [])

  const handleChatScroll = useCallback(() => {
    const el = chatListRef.current
    if (!el) return
    const pinned = isNearBottom(el)
    pinnedRef.current = pinned
    if (pinned) {
      setHasUnreadBelow(false)
    }
  }, [])

  const onSend = useCallback(async () => {
    const text = message.trim()
    if (!text || sending) return
    setMessage('')
    // FE-03：主聊天入口默认流式；非流式 send 保留为回退（send，当前未被 UI 使用）。
    await streamSend(text)
    scrollToBottom()
  }, [message, sending, streamSend, scrollToBottom])

  const onConfirm = useCallback(
    async (action: 'confirm' | 'reject', item: ChatConfirmItem) => {
      await handleConfirmAction(action, item)
      scrollToBottom()
    },
    [handleConfirmAction, scrollToBottom]
  )

  // 挂载：加载今日会话 + 待确认恢复 + 启动轮询（StrictMode 安全：清理由 useChat/unmount 完成）
  useEffect(() => {
    let cancelled = false
    const init = async () => {
      const date = today()
      await loadConversation(date)
      if (cancelled) return
      await restorePendingConfirmations(date)
      if (cancelled) return
      scrollToBottom(true)
      hasInitializedScrollRef.current = true
      startConversationSync(date, {
        onAfterSync: () => {
          scrollToBottom()
        },
      })
    }
    void init()
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // 新消息上屏 → 按吸附状态决定滚动或未读提示
  useEffect(() => {
    const current = messages.length
    const previous = prevMessageCountRef.current
    prevMessageCountRef.current = current
    if (!hasInitializedScrollRef.current || current <= previous) return
    scrollToBottom()
  }, [messages.length, scrollToBottom])

  const renderChatItem = (m: ChatItem) => {
    if (m.kind === 'message') {
      return (
        <Box
          p="8px 14px"
          maw="75%"
          style={{
            borderRadius: 'var(--radius-lg)',
            borderBottomRightRadius: m.role === 'user' ? 6 : undefined,
            borderBottomLeftRadius: m.role === 'cornie' ? 6 : undefined,
            background: m.role === 'user' ? 'var(--color-accent)' : 'var(--color-surface-2)',
            color: m.role === 'user' ? 'var(--color-surface)' : 'var(--color-text)',
          }}
        >
          <Text fz="var(--text-xs)" opacity={0.6} mb={2}>
            {m.role === 'user' ? '你' : '铃湾'}
          </Text>
          <Text fz="var(--text-md)" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>
            {m.content}
          </Text>
        </Box>
      )
    }
    if (m.kind === 'tool_result') {
      return <ToolResultPanel results={m.results} />
    }
    if (m.kind === 'confirm') {
      return (
        <ConfirmCard
          request={m.request}
          status={m.status || 'pending'}
          errorMessage={m.errorMessage || ''}
          onConfirm={() => void onConfirm('confirm', m)}
          onReject={() => void onConfirm('reject', m)}
        />
      )
    }
    if (m.kind === 'ask_back') {
      return <AskBackBubble question={m.question} reason={m.reason} />
    }
    // kind === 'error'
    return (
      <Box
        p="8px 14px"
        maw="100%"
        style={{
          borderRadius: 'var(--radius-lg)',
          background: 'var(--color-danger-soft)',
          color: 'var(--color-danger)',
        }}
      >
        <Text fz="var(--text-xs)" opacity={0.6} mb={2}>
          系统提示
        </Text>
        <Text fz="var(--text-md)" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>
          {m.content}
        </Text>
      </Box>
    )
  }

  return (
    <Stack
      gap={0}
      h="100%"
      style={{ background: 'var(--color-surface)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' }}
    >
      {/* 顶部陪伴区 */}
      <Group
        align="baseline"
        gap={12}
        px={20}
        py={8}
        wrap="nowrap"
        style={{
          borderBottom: '1px solid var(--color-border)',
          background: 'var(--color-tint-chat)',
          flex: '0 0 auto',
        }}
      >
        <Text fz="var(--text-md)" fw={700} style={{ whiteSpace: 'nowrap' }}>
          {greeting}
        </Text>
        <Text fz="var(--text-sm)" c="dimmed">
          {todayDate}
        </Text>
        <Button variant="subtle" size="compact-sm" ml={6} onClick={() => navigate('/chat/history')}>
          翻看以前聊天
        </Button>
        <Text fz="var(--text-sm)" c="dimmed" ml="auto">
          想和我聊点什么？
        </Text>
      </Group>

      {/* 主对话区 */}
      <Box
        ref={chatListRef}
        onScroll={handleChatScroll}
        style={{
          flex: 1,
          overflowY: 'auto',
          padding: '14px 20px',
          scrollBehavior: 'smooth',
          position: 'relative',
          minHeight: 0,
        }}
      >
        {messages.length === 0 && !sending ? (
          <EmptyState
            h="100%"
            icon={<IconMessageCircle size={32} stroke={1.5} />}
            title="给铃湾发一条消息吧"
            style={{ justifyContent: 'center' }}
          />
        ) : (
          <Stack gap={10}>
            {messages.map((m) => (
              <Box
                key={m.id}
                w="100%"
                style={{
                  display: 'flex',
                  justifyContent: m.kind === 'message' && m.role === 'user' ? 'flex-end' : 'flex-start',
                }}
              >
                {renderChatItem(m)}
              </Box>
            ))}
            {sending ? (
              <Box
                p="8px 14px"
                maw="75%"
                style={{
                  borderRadius: 'var(--radius-lg)',
                  borderBottomLeftRadius: 6,
                  background: 'var(--color-surface-2)',
                  color: 'var(--color-text)',
                }}
              >
                <Text fz="var(--text-xs)" opacity={0.6} mb={2}>
                  铃湾
                </Text>
                <Text fz="var(--text-md)" opacity={0.6} style={{ fontStyle: 'italic' }}>
                  正在思考...
                </Text>
              </Box>
            ) : null}
          </Stack>
        )}

        {hasUnreadBelow ? (
          <Button
            variant="light"
            size="compact-sm"
            w="fit-content"
            ml="auto"
            mt={12}
            style={{ position: 'sticky', left: '100%', bottom: 10, display: 'inline-flex' }}
            onClick={() => scrollToBottom(true)}
          >
            回到底部
          </Button>
        ) : null}
      </Box>

      {/* 输入区 */}
      <Group
        align="flex-end"
        gap={8}
        px={16}
        py={10}
        wrap="nowrap"
        style={{ borderTop: '1px solid var(--color-border)', background: 'var(--color-surface)', flex: '0 0 auto' }}
      >
        <Textarea
          flex={1}
          autosize
          minRows={1}
          maxRows={4}
          placeholder="和铃湾说句话..."
          value={message}
          onChange={(e) => setMessage(e.currentTarget.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
              e.preventDefault()
              void onSend()
            }
          }}
          styles={{
            input: {
              minHeight: 36,
              resize: 'none',
              background: 'var(--color-bg)',
              color: 'var(--color-text)',
            },
          }}
        />
        <Button
          disabled={!message.trim() || sending}
          onClick={() => void onSend()}
          style={{ flex: '0 0 auto', whiteSpace: 'nowrap' }}
        >
          发送
        </Button>
      </Group>

      {/* 待确认提示 */}
      {pendingCount > 0 ? (
        <Text
          ta="center"
          fz="var(--text-sm)"
          c="dimmed"
          px={20}
          py={6}
          style={{ background: 'var(--color-tint-chat)', borderTop: '1px solid var(--color-border)' }}
        >
          有 {pendingCount} 条待确认事项，请在上面处理。
        </Text>
      ) : null}
    </Stack>
  )
}
