// src/renderer/components/AskBackBubble.vue
<script setup>
defineProps({
  question: {
    type: String,
    default: '',
  },
  reason: {
    type: String,
    default: '',
  },
})
</script>

<template>
  <div class="askBackBubble">
    <div class="askBackRole">Cornie 还想确认一下</div>
    <div class="askBackQuestion">{{ props.question }}</div>
    <div v-if="props.reason" class="askBackReason">
      <span class="askBackReasonLabel">原因：</span>{{ props.reason }}
    </div>
  </div>
</template>

<style scoped>
/* FE-10：配色对齐全局暖色主题（原深蓝黑底为旧样式残留）。 */
.askBackBubble {
  width: 100%;
  padding: 10px 12px;
  border-radius: var(--radius-lg);
  background: color-mix(in srgb, var(--color-accent) 6%, transparent);
}

.askBackRole {
  font-size: var(--text-xs);
  color: var(--muted);
}

.askBackQuestion {
  margin-top: 4px;
  font-size: var(--text-sm);
  line-height: 1.5;
  color: inherit;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

.askBackReason {
  margin-top: 6px;
  font-size: var(--text-xs);
  line-height: 1.45;
  color: var(--muted);
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

.askBackReasonLabel {
  color: inherit;
}
</style>

// src/renderer/components/chat/AskBackBubble.tsx
import { Paper, Stack, Text } from '@mantine/core'

// 追问气泡（React 版 AskBackBubble.vue）：策略引擎 ask_back 决策上屏。
// FE-10：配色对齐全局暖色主题（brand.0 = accent 6% 混白底，与旧 color-mix 等价）。

export default function AskBackBubble({ question, reason }: { question: string; reason?: string }) {
  return (
    <Paper w="100%" p="10px 12px" radius="lg" bg="brand.0" shadow="0">
      <Stack gap={4}>
        <Text fz="var(--text-xs)" c="dimmed">
          Cornie 还想确认一下
        </Text>
        <Text fz="var(--text-sm)" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>
          {question}
        </Text>
        {reason ? (
          <Text fz="var(--text-xs)" c="dimmed" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>
            <span style={{ color: 'inherit' }}>原因：</span>
            {reason}
          </Text>
        ) : null}
      </Stack>
    </Paper>
  )
}
